repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1
    hooks:
      - id: check-json
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: check-added-large-files
  - repo: local
    hooks:
      - id: isort
        name: isort
        language: python
        types: [python]
        entry: isort
      - id: autopep8
        name: autopep8
        language: python
        types: [python]
        entry: autopep8
      - id: flake8
        name: flake8
        language: python
        types: [python]
        entry: flake8
  - repo: https://github.com/psf/black
    rev: 22.3.0
    hooks:
      - id: black
exclude: '^notebooks/'
